### ISSUE TITLE
Surprising behaviour when setting and then getting simulator variables

### ISSUE THREAD

**Issue by kyllingstad** [open-simulation-platform/libcosim#535]
The following pseudocode illustrates the problem:
```.cpp
simulator sim;
sim.expose_for_setting(inputVar);
sim.expose_for_getting(inputVar);

sim.set_real(inputVar, someValue);
assert(sim.get_real(inputVar) == someValue); // FAILS
```
Naïvely, one would expect the last statement to succeed, but in general it doesn't. The reason is that the underlying implementation of the `simulator` interface, `slave_simulator`, uses separate buffers for its get and set operations. This means that the value only gets transferred from the "set buffer" to the "get buffer" when `do_iteration()` or `do_step()` is called.

I vaguely recall that we discussed this once, but I don't remember what the outcome was, and I couldn't find any other report of it here. So I figured I'd post this to at least document the issue.

Is the current behaviour desirable, or at the very least acceptable? If not, how do we deal with it?

**Comment by eidekrist** [comment]
I too have accepted this as a feature. Even if this is solved in `slave_simulator`, observation of variable values only occurs following a step. Client code (using an execution with observers) won't be able to "see" the updated input value until after a call has been placed to `simulator.do_step()`.

**Comment by kyllingstad** [comment]
Ok, good. Closing this, then.
