### ISSUE TITLE
Add @conan/stable to zlib and bzip2 in conanfile.py 

### ISSUE THREAD

**Issue by THEvang** [open-simulation-platform/libcosim#552]
I get errors when running `conan install .. --build=missing`:

`ERROR: 404: Not Found. [Remote: conan-center]
The 'bzip2/1.0.8' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.`

Conan finds the dependencies if I add @conan/stable to both bzip2 and zlib in conanfile.py.

**Comment by markaren** [comment]
I reckon it's fine to close this issue..
