### ISSUE TITLE
Update Conan packages

### ISSUE THREAD

**Issue by ljamt** [open-simulation-platform/libcosim#563]
Base on Ubuntu LTS 20.04

**Comment by kyllingstad** [comment]
Originally posted on Slack:
>Previously, we've discussed switching to the Ubuntu 20.04 runners for our GitHub workflows. I no longer think that's a good idea. We did that for some other stuff my group has published on GitHub, and it turned out that I couldn't use the resulting Conan packages on my Debian Stable box, despite the GCC version matching and everything. The reason is that the GLIBC (the GNU standard C library) is versioned separately from GCC, and depends as much on the OS as on the GCC version you're using. That is, a newer OS can use a newer GLIBC version for the same GCC version.
>
> And here's the catch: GLIBC is forwards-compatible, meaning that everything works out well if the following condition is satisfied:
>
>     (compile-time GLIBC version) <= (run-time GLIBC version)
>
> Otherwise, you may run into trouble. (I did.)
>
> So the lesson I learned is, use as new a compiler version as you want, but compile on an OS which is as old as possible.

**Comment by kyllingstad** [comment]
#747 updates dependencies and changes the CI build environments to the standard Conan build images (for Conan builds) and Debian Stable (for non-Conan builds).
