### ISSUE TITLE
Process hangs when loading OspSystemStructure.xml with invalid parameter name

### ISSUE THREAD

**Issue by ljamt** [open-simulation-platform/libcosim#597]
Have not done any debugging with libcosim, but experiencing the following in the applications.

*Cosim Demo App:*
Application hangs when loading a OspSystemStructure.xml defining initial value for a **non-existing** variable. Invalid configuration should have been detected and error message given to the user.

*cosim*
 application hangs on cosim run `path-to-invalid-config`

**Comment by eidekrist** [comment]
I have tested this with the following Windows builds:
- cosim-demo-app v0.7.0 - release
- cosim-demo-app current dev version - debug
- libcosimc 0.8.0 - debug
- cosim 0.8.0 - debug
- libcosim 0.8.0 - debug

I cannot reproduce this with an OspSystemStructure.xml specifying an initial value for a non-existing variable. Do you have a setup you can share?

**Comment by ljamt** [comment]
> Do you have a setup you can share?

Sent you an example by email.

**Comment by eidekrist** [comment]
> Sent you an example by email.

From debugging it looks like our old friend *terminate before initialize*. Some FMU's don't handle this very well, and I think that is what is happening here. It should be solvable by validating initial values before loading FMUs.
