### ISSUE TITLE
Please log in to "osp" to perform this action

### ISSUE THREAD

**Issue by andre2007** [open-simulation-platform/libcosim#608]
As far as I understand the error log, you cannot use conan without registration? Could you add to the README where I have to register and maybe the missing conan login commands?

``` dockerfile
FROM debian:buster

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y curl unzip build-essential gcc cmake python3-pip
    
RUN pip3 install conan

RUN curl -L -o libcosim.zip https://github.com/open-simulation-platform/libcosim/archive/v0.7.0.zip \
    && unzip libcosim.zip -d / \
    && cd /libcosim-0.7.0 \
    && mkdir build \
    && cd build \
    && conan remote add osp https://osp.jfrog.io/artifactory/api/conan/conan-public \
    && conan install .. -s build_type=Release --build=missing -o fmuproxy=True --settings=compiler.libcxx=libstdc++11
```

> fmilibrary/2.0.3: Not found in local cache, looking in remotes...
fmilibrary/2.0.3: Trying with 'conan-center'...
fmilibrary/2.0.3: Trying with 'osp'...
Please log in to "osp" to perform this action. Execute "conan user" command.
Remote 'osp' username: ERROR: Failed requirement 'fmilibrary/2.0.3' from 'conanfile.py (libcosim/0.7.0)'
ERROR: EOF when reading a line. [Remote: osp]

**Comment by markaren** [comment]
Looks like the newly updated osp remote needs credentials (which it should not). @hplatou

**Comment by hplatou** [comment]
We are in the middle of a process to move to a new Conan repository(you are using the new correct url) and the permissions were not set correctly. I have updated now so please try again.

**Comment by andre2007** [comment]
You might have to adapt the README, as there are some more flags needed:

ERROR: Failed requirement 'fmilibrary/2.0.3' from 'conanfile.py (libcosim/0.7.0)'
ERROR: The remote at 'https://osp.jfrog.io/artifactory/api/conan/conan-public' only works with revisions enabled. Set CONAN_REVISIONS_ENABLED=1 or set 'general.revisions_enabled = 1' at the 'conan.conf'. [Remote: osp]

**Comment by andre2007** [comment]
Also just setting the revisions enabled flag does not work:
`conan install .. -s build_type=Release --build=missing -o fmuproxy=True --settings=compiler.libcxx=libstdc++11 --settings=general.revisions_enabled=1`

ERROR: general not defined for general.revisions_enabled
Please define general value first too

**Comment by markaren** [comment]
Yeah, setting the `CONAN_REVISIONS_ENABLED="1"` needs to be documented.
