### ISSUE TITLE
Libcosim fails to compile with Visual Studio 2019

### ISSUE THREAD

**Issue by hplatou** [open-simulation-platform/libcosim#621]
Visual Studio 2019 report warnings during compilation of libcosim:

`warning C5205: delete of an abstract class 'cosim::function' that has a non-virtual destructor results in undefined behavior`

This is reported for every class implementing the `function` interface and by default warnings will fail the build.

**Comment by kyllingstad** [comment]
Oops, looks like I forgot to declare
```cpp
virtual ~function() = default;
```
in the definition of `class function`. I believe the same goes for `function_type`.
