### ISSUE TITLE
Not finding a variable in the model description is not exceptional

### ISSUE THREAD

**Issue by THEvang** [open-simulation-platform/libcosim#669]
Searching for a variable, but not finding it is not exceptional nor an error. I think it would be clearer to return an optional value containing a variable description

https://github.com/open-simulation-platform/libcosim/blob/22a89c439970a2e2588ed5e90082e6e892274aeb/src/cosim/model_description.cpp#L21

**Comment by kyllingstad** [comment]
Completely agree. As a general convention, I think any function whose name starts with `find` should always return some kind of null value if it *can't* find what it's looking for.
