### ISSUE TITLE
System wide boost is preferred over Conan installed boost

### ISSUE THREAD

**Issue by THEvang** [open-simulation-platform/libcosim#682]
If boost is installed on your system libcosim will use the system wide installation rather than the conan installed version even if LIBCOSIM_USE_CONAN=True is defined. I had to remove the system wide installation in order to build libcosim.

CNake configuration log is attached

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Current libcosim version: 0.8.3

-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /home/thomas/Repositories/libcosim/build
-- Conan: Compiler GCC>=5, checking major version 9.3
-- Conan: Checking correct version: 9.3
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_fiber"
  (requested version 1.71.0) with any of the following names:

    boost_fiberConfig.cmake
    boost_fiber-config.cmake

  Add the installation prefix of "boost_fiber" to CMAKE_PREFIX_PATH or set
  "boost_fiber_DIR" to a directory containing one of the above files.  If
  "boost_fiber" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  CMakeLists.txt:110 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/thomas/Repositories/libcosim/build/CMakeFiles/CMakeOutput.log".

**Comment by kyllingstad** [comment]
This is no longer a problem with Conan 2 (see #747) because it generates package configuration files that will take precedence over “find scripts”.
