### ISSUE TITLE
Conan v2 combability

### ISSUE THREAD

**Issue by markaren** [open-simulation-platform/libcosim#718]
Recipes across the OSP organization are not conan v2 compatible and will stop working at some point. They should be updated sooner than later.

https://docs.conan.io/en/latest/migrating_to_2.0/recipes.html

**Comment by kyllingstad** [comment]
I'll do this as a precursor to #741.

@joakimono currently has a Conan 2 recipe for FMI library under review for conan-center; see conan-io/conan-center-index#20256. When that is in, we'll work towards packaging FMI Library 3.x too (currently in alpha). We can then start working in parallel on FMI 3.0 support in libcosim.
