### ISSUE TITLE
Specify compatible Conan versions

### ISSUE THREAD

**Issue by theBadMusician** [open-simulation-platform/libcosim#738]
Currently, it seems like only Conan versions 1.xx are supported by the project. As the LTS Conan version is the latest major.minor release (2.0.7 at the time of this issue), it should at least be specified in the README that only 1.xx versions are supported.

More long-term, the project should be updated to support Conan versions >2.0, referring to #718

**Comment by kyllingstad** [comment]
Fixed by #745.
